### ISSUE TITLE
Unable to install via pip

### ISSUE THREAD

**Issue by MSA8D8** [mne-tools/mne-realtime#12]
Hi!

I tried to install the mne_realtime library from the pip command, "pip install mne_realtime",  but I am faced with an error message below. My PC is MacBook Pro 2014 Mid.

> MasarunoMacBook-puro:~ masaru$ pip install mne_realtime
Collecting mne_realtime
ERROR: Could not find a version that satisfies the requirement mne_realtime (from versions: none)
ERROR: No matching distribution found for mne_realtime

And, I found that there is another person who has suffered from the same problem.
https://www.reddit.com/r/neuro/comments/d08exy/realtime_analysis_coming_from_mne_python/

So, please help me to install this library via pip.

Thank you in advance.

P.S.
I know that I can install this library by typing the command "python setup.py install" from the "mne_realtime" directory I download from GitHub. But, the pip doesn't work properly.

**Comment by teonbrooks** [comment]
hi @MSA8D8, we haven't released mne_realtime on pip yet. I think once we add the fieldtrip buffer back, we will likely cut a 0.1 release

**Comment by jasmainak** [comment]
you can use:

```sh
$ pip install https://api.github.com/repos/autoreject/autoreject/zipball/master
```

for now. There will be a fix soon.

**Comment by larsoner** [comment]
I think you missed a couple of URL changes :)

```
$ pip install https://api.github.com/repos/mne-tools/mne-realtime/zipball/master
```

**Comment by jasmainak** [comment]
I thought it would pass unnoticed my attempt at promoting autoreject ... ;)
