### ISSUE TITLE
Make BrainVision Client

### ISSUE THREAD

**Issue by alexrockhill** [mne-tools/mne-realtime#15]
It would be helpful for the Martinos group @emacadams to have a BrainVision client. 
[RDA_Client_Python_EN.pdf](https://github.com/mne-tools/mne-realtime/files/3687611/RDA_Client_Python_EN.pdf)

Weirdly it looks like it's written in Python 2.6
[RDA_Client_Python.zip](https://github.com/mne-tools/mne-realtime/files/3687618/RDA_Client_Python.zip)

...

**Comment by teonbrooks** [comment]
hey @alexrockhill, the idea we had about the LSLClient is that it could be a general purpose way to handle hardware as LSL team has worked to support those hardware. would it work to use LSL instead?

**Comment by jasmainak** [comment]
There is also access through FieldTrip client: http://www.fieldtriptoolbox.org/development/realtime/rda/

**Comment by alexrockhill** [comment]
I will let @emacadams reopen if she ever wants to move away from the MATLAB-based TMS-EEG real-time visualization as I don't have a BV system to work with anymore.
