### ISSUE TITLE
 Emotiv EPOC+ Real Time Data Processing in MNE Python

### ISSUE THREAD

**Issue by Melvin555** [mne-tools/mne-realtime#20]
Hello MNE developers, I have got an issue when I tried to have a real time reading using a commercial EEG brand, Emotiv. I have tried to tweak a bit the code from "Compute real-time evoked response with FieldTrip client" ->https://martinos.org/mne/stable/auto_examples/realtime/ftclient_rt_average.html, because I used to run FieldTrip buffer. But unfortunately, I ran into an error with the traceback:
.
.
.
FieldTripClient: Waiting for server to start
FieldTripClient: Connected
FieldTripClient: Retrieving header
FieldTripClient: Header retrieved
Info dictionary not provided. Trying to guess it from FieldTrip Header object
<ipython-input-2-5faefdbe070a>:2: RuntimeWarning: Info dictionary not provided. Trying to guess it from FieldTrip Header object
  tmax=150, wait_max=10) as rt_client:
Traceback (most recent call last):
 
  File "<ipython-input-2-5faefdbe070a>", line 2, in <module>
    tmax=150, wait_max=10) as rt_client:
 
  File "C:\ProgramData\Anaconda3\lib\site-packages\mne\realtime\fieldtrip_client.py", line 111, in __enter__
    self.info = self._guess_measurement_info()
 
  File "C:\ProgramData\Anaconda3\lib\site-packages\mne\realtime\fieldtrip_client.py", line 159, in _guess_measurement_info
    int(re.findall(r'[^\W\d_]+|\d+', ch)[-1])
 
ValueError: invalid literal for int() with base 10: 'GYROX' 
.
.
.

The latest suggestion after the discussions with some of the core developers: 
-> instead of using raw_info = rt_client.get_measurement_info(), try to create my own info using mne function create_info. And I am working on it now.
Any other suggestion for solving this issue will be very welcome :)

**Comment by jasmainak** [comment]
I had completely missed this. Thanks for transferring the issue @teonbrooks 

@Melvin555 are you still interested in a solution to this? You will need to provide the `info` by reading in a small recording to the `FieldTripClient` object: https://mne.tools/mne-realtime/generated/mne_realtime.FieldTripClient.html#mne_realtime.FieldTripClient

**Comment by Melvin555** [comment]
Hello Mainak Jas @jasmainak 
I think that time I moved on to use some other tools. Thank you for sending me this better documentation. It will be useful in my next project :)
