### ISSUE TITLE
To Do: Project Cleanup

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-realtime#24]
- [ ] Currently some of the urls don't work in the docs.
- [ ] There are dependencies that aren't listed for some of the examples.
- [ ] We need to create a script that can be run if neuromag2ft isn't installed
- [ ] Make a copy of the modified neuromag2ft files to the mne-realtime module

**Comment by timonmerk** [comment]
Just some additional explanation: 
The website API call results in the following link https://mne.tools/mne-realtime/%3Chttps://mne.tools/mne-realtime/api.html%3E, which is not callable. 

Then it would great to adapt the example/plot_ftclient_rt_average.py the following explanation: 

> 
> This example was tested in simulation mode:
> 
> .. code-block:: console
> 
>     $ neuromag2ft --file MNE-sample-data/MEG/sample/sample_audvis_raw.fif
> 
> using a modified version of ``neuromag2ft`` available
> `here <https://staff.washington.edu/larsoner/minimal_cmds.tar.gz>`__
> to run the FieldTrip buffer. Then running this example acquires the
> data on the client side.

Currently I am also unsure how neuromag2ft should be installed from the mentioned website.

**Comment by jasmainak** [comment]
you should just download it and untar it. It should work on a 64 bit Linux machine. If you don't have that, the binary won't run I think ...

**Comment by teonbrooks** [comment]
I think what @timonmerk is highlighting is that we could be doing the hosting of this file so it doesn't look like the user is downloading an arbitrary file from the web.
we could also do this download step for those who don't have it, similar to how we do data download for `sample_data`
