### ISSUE TITLE
ImportError: cannot import name '_check_pylsl_installed' from 'mne.utils' 

### ISSUE THREAD

**Issue by Marou-c** [mne-tools/mne-realtime#34]
Hi,

I am trying to use mne real-rime and I get this error:
_ImportError: cannot import name '_check_pylsl_installed' from 'mne.utils'_ 
It is used in LSL_Client.py

I checked mne/utils repo on github and there is no such a file, so it is not an issue with a missing file in my environment.

I am a beginner, so maybe I'm missing something?

Thanks

**Comment by Asudy** [comment]
I also got this bug and was about to submit an issue when I saw you did it just 15 hours ago.

thx again for the really quick solution offered by developers!
