### ISSUE TITLE
Add conda-forge package?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-realtime#36]
Hello, I just wanted to ask if you'd be interested in a `conda-forge` package of MNE-Realtime? I could build one.

Asking because I'm right now looking at packages that would be nice to include in the [MNE installers](https://github.com/hoechenberger/mne-installers).

Is this package already compatible with the upcoming 1.0 release of MNE-Python?

**Comment by larsoner** [comment]
That would be great, feel free to do it @hoechenberger !

Same for MNE-connectivity, I think just nobody has gotten around to doing it yet

**Comment by hoechenberger** [comment]
It appears there are no tagged or packaged releases of this package. Would it be possible to make a quick release here on GitHub, at least?

**Comment by larsoner** [comment]
Go go @hoechenberger !

https://pypi.org/project/mne-realtime/

**Comment by hoechenberger** [comment]
@larsoner Could you push the sdists to PyPI too, in addition to the wheels? I need the sdists for conda-forge.
Thank you!

**Comment by larsoner** [comment]
Done

https://pypi.org/project/mne-realtime/#files

**Comment by hoechenberger** [comment]
Merci !
